spring:
  application:
    name: statistics-server

server:
  port: ${PORT:8502}

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

