spring:
  application:
    name: statistics-server
  rabbitmq:
    host: localhost
    port: 5672
    username: tsservice
    password: tsservice

server:
  port: ${PORT:8501}

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}

rabbitmq:
  tick:
    queue:
      name: tick-queue
    exchange:
      name: tick-exchange
    routing:
      name: tick-routing
  calculation:
    queue:
      name: calculation-queue
    exchange:
      name: calculation-exchange
    routing:
      name: calculation-routing

tick:
  sliding:
    time:
      interval: 60000

